Sync .github/workflows/pull-request.yml.

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -93,15 +93,18 @@ jobs:
 
       - name: Run rewrite-maven-plugin and commit changes
         run: |
-          # Run the rewrite plugin to make actual changes
           just rewrite-run
 
-          # Commit the changes if any files were modified
           if [[ -n $(git status --porcelain) ]]; then
+            FIX_BRANCH="fix-${{ github.event.pull_request.number }}-rewrite"
+            git switch --create $FIX_BRANCH
+
             git add --all
-            git commit -m "Auto-fix: Apply OpenRewrite recipe changes"
-            git push
-            echo "Committed and pushed OpenRewrite fixes"
+            git commit --message "Auto-fix: Apply OpenRewrite recipe changes"
+            git push origin $FIX_BRANCH
+
+            echo "OpenRewrite fixes have been pushed to the $FIX_BRANCH branch."
+            exit 1
           else
             echo "No changes needed by OpenRewrite"
           fi
@@ -150,7 +153,7 @@ jobs:
             git commit --message "Auto-fix: Apply Spotless POM formatting"
             git push origin $FIX_BRANCH
 
-            echo "Spotless fixes have been pushed to the $FIX_BRANCH branch."
+            echo "Spotless POM fixes have been pushed to the $FIX_BRANCH branch."
             exit 1
           else
             echo "No changes needed by Spotless POM"
@@ -190,15 +193,18 @@ jobs:
 
       - name: Run Spotless Apply for Java
         run: |
-          # Run spotless for java
           just spotless java
 
-          # Commit the changes if any files were modified
           if [[ -n $(git status --porcelain) ]]; then
+            FIX_BRANCH="fix-${{ github.event.pull_request.number }}-spotless-java"
+            git switch --create $FIX_BRANCH
+
             git add --all
-            git commit -m "Auto-fix: Apply Spotless Java formatting"
-            git push
-            echo "Committed and pushed Spotless fixes"
+            git commit --message "Auto-fix: Apply Spotless Java"
+            git push origin $FIX_BRANCH
+
+            echo "Spotless Java fixes have been pushed to the $FIX_BRANCH branch."
+            exit 1
           else
             echo "No changes needed by Spotless"
           fi
@@ -237,15 +243,18 @@ jobs:
 
       - name: Run Spotless Apply for Prettier Java with Sorted Imports
         run: |
-          # Run spotless for prettier-java-sort-imports
           just spotless prettier-java-sort-imports
 
-          # Commit the changes if any files were modified
           if [[ -n $(git status --porcelain) ]]; then
+            FIX_BRANCH="fix-${{ github.event.pull_request.number }}-spotless-prettier-java-sort-imports"
+            git switch --create $FIX_BRANCH
+
             git add --all
-            git commit -m "Auto-fix: Apply Spotless Prettier Java with Sorted Imports"
-            git push
-            echo "Committed and pushed Spotless fixes"
+            git commit --message "Auto-fix: Apply Spotless Prettier Java with Sorted Imports"
+            git push origin $FIX_BRANCH
+
+            echo "Spotless Prettier Java with Sorted Imports fixes have been pushed to the $FIX_BRANCH branch."
+            exit 1
           else
             echo "No changes needed by Spotless"
           fi
@@ -284,17 +293,75 @@ jobs:
 
       - name: Run Spotless Apply for Java Cleanthat
         run: |
-          # Run spotless for java-cleanthat
           just spotless java-cleanthat
 
-          # Commit the changes if any files were modified
           if [[ -n $(git status --porcelain) ]]; then
+            FIX_BRANCH="fix-${{ github.event.pull_request.number }}-spotless-java-cleanthat"
+            git switch --create $FIX_BRANCH
+
             git add --all
-            git commit -m "Auto-fix: Apply Spotless Java Cleanthat formatting"
-            git push
-            echo "Committed and pushed Spotless fixes"
+            git commit --message "Auto-fix: Apply Spotless Java Cleanthat formatting"
+            git push origin $FIX_BRANCH
+
+            echo "Spotless Java Cleanthat fixes have been pushed to the $FIX_BRANCH branch."
+            exit 1
           else
             echo "No changes needed by Spotless"
+          fi
+
+      # Remove any jars we may have created before actions/cache caches .m2
+      - name: "Clean Maven cache"
+        run: rm -rf ~/.m2/repository/${{ env.GROUP_ID }}
+
+  errorprone-fix:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      pull-requests: write
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - uses: actions/cache@v4
+        with:
+          key: maven-errorprone-${{ hashFiles('**/pom.xml') }}
+          path: ~/.m2/repository
+          restore-keys: |
+            maven-errorprone-
+            maven-
+
+      - uses: twosigma/maven-cache-cleaner@v1
+
+      - uses: jdx/mise-action@v2
+
+      - name: Configure Git
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "github-actions@github.com"
+
+      - name: Run Error Prone
+        run: |
+          just errorprone-patch
+
+          find . -name "error-prone.patch" -type f | while read -r patch_file; do
+            echo "Applying patch file: $patch_file"
+            patch -p0 -u -i "$patch_file"
+          done
+
+          if [[ -n $(git status --porcelain) ]]; then
+            FIX_BRANCH="fix-${{ github.event.pull_request.number }}-errorprone"
+            git switch --create $FIX_BRANCH
+
+            git add --all
+            git commit --message "Auto-fix: Apply Error Prone fixes"
+            git push origin $FIX_BRANCH
+
+            echo "Error Prone fixes have been pushed to the $FIX_BRANCH branch."
+            exit 1
+          else
+            echo "No changes needed by Error Prone"
           fi
 
       # Remove any jars we may have created before actions/cache caches .m2
@@ -333,15 +400,18 @@ jobs:
         env:
           LIFTWIZARD_FILE_MATCH_RULE_RERECORD: true
         run: |
-          # Run Maven with file match rule rerecord enabled
           just mvn
 
-          # Commit the changes if any files were modified
           if [[ -n $(git status --porcelain) ]]; then
+            FIX_BRANCH="fix-${{ github.event.pull_request.number }}-liftwizard-file-match-rerecord"
+            git switch --create $FIX_BRANCH
+
             git add --all
-            git commit -m "Auto-fix: Update file match test expectations"
-            git push
-            echo "Committed and pushed updated test expectations"
+            git commit --message "Auto-fix: Update file match test expectations"
+            git push origin $FIX_BRANCH
+
+            echo "Updated Liftwizard test expectations have been pushed to the $FIX_BRANCH branch."
+            exit 1
           else
             echo "No changes needed in test expectations"
           fi
